version: '3'

services:
  backend:
    build: ./python
    container_name: gen-salim-backend
    networks:
      br0:
        ipv4_address: '10.0.3.91'
    environment:
      - TOKEN

networks:
  br0:
    external:
      name: br0
